from django.urls import path
from . import views
urlpatterns = [
    path('', views.index),
    path('filter/<str:category>/', views.filter),
    path('search/', views.search),
    path('search/remove/', views.remove_search),
    path('sort/', views.sort),
    path('product/<int:id>/', views.product),
    path('product/<int:id>/add/', views.add_to_cart),
    path('cart/', views.cart),
    path('cart/product/<int:id>/remove/', views.remove_from_cart),
    path('cart/product/<int:id>/change/', views.change_quantity),
    path('cart/promo/', views.promo),
    path('cart/promo/remove/', views.remove_promo),
    path('checkout/', views.checkout),
    path('checkout/continue/<int:id>/', views.continue_checkout),
    path('checkout/return/', views.return_checkout),
    path('checkout/order/<int:id>/', views.create_order),
    path('checkout/order/<order_id>/capture/<int:id>/', views.capture_order),
    path('checkout/order/placed/', views.order_placed),
    path('thankyou/', views.thank_you),
    path('review/<int:id>/', views.review),
    path('review/<int:id>/submit/', views.submit_review),
    path('review/<int:id>/update/', views.update_review),
    path('review/<int:id>/update/cancel/', views.cancel_update_review),
    path('review/<int:id>/sort/', views.sort_reviews),
    path('contact/', views.contact),
    path('contact/submit/', views.submit_contact),
]
