# Generated by Django 2.2 on 2021-01-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_remove_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
