# Generated by Django 2.2 on 2021-01-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_auto_20210129_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='promo',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
