# Generated by Django 2.2 on 2021-01-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_auto_20210130_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='promo',
            name='discount',
            field=models.FloatField(),
        ),
    ]
