# Generated by Django 2.2 on 2021-01-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_auto_20210130_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='discount',
            field=models.FloatField(null=True),
        ),
    ]
