# Generated by Django 2.2 on 2021-02-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0012_auto_20210202_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
