# Generated by Django 2.2 on 2021-02-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0014_auto_20210205_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(related_name='product', to='shop_app.Image'),
        ),
    ]
