# Generated by Django 2.2 on 2021-02-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0015_auto_20210205_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
    ]
