# Generated by Django 2.2 on 2021-02-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0019_auto_20210205_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
