# Generated by Django 2.2 on 2021-02-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0021_auto_20210205_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=255),
        ),
    ]
