# Generated by Django 2.2 on 2021-02-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0022_auto_20210205_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='body',
        ),
    ]
