# Generated by Django 2.2 on 2021-02-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0024_auto_20210206_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
