# Generated by Django 2.2 on 2021-02-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0028_auto_20210210_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
