# Generated by Django 2.2 on 2021-02-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0029_auto_20210211_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
