# Generated by Django 2.2 on 2021-02-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0030_auto_20210211_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
