# Generated by Django 2.2 on 2021-02-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0031_review_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
