# Generated by Django 2.2 on 2021-02-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0032_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
