# Generated by Django 2.2 on 2021-02-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0034_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('district_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
