# Generated by Django 2.2 on 2021-02-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0035_taxstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxstate',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
