# Generated by Django 2.2 on 2021-02-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0038_auto_20210218_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
