# Generated by Django 2.2 on 2021-02-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0039_auto_20210218_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='tax_rate',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='promo',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='state',
            name='tax_rate',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
    ]
