# Generated by Django 2.2 on 2021-02-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0040_auto_20210218_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='carrier',
            field=models.CharField(default='', max_length=255),
        ),
    ]
