# Generated by Django 2.2 on 2021-02-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0041_shippingmethod_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='carrier',
            field=models.CharField(max_length=255),
        ),
    ]
