# Generated by Django 2.2 on 2021-02-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0042_auto_20210220_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingmethod',
            old_name='carrier',
            new_name='service',
        ),
    ]
