# Generated by Django 2.2 on 2021-02-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0043_auto_20210221_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='mail_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
