# Generated by Django 2.2 on 2021-02-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0044_shippingmethod_mail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='mail_type',
            field=models.CharField(max_length=255),
        ),
    ]
