# Generated by Django 2.2 on 2021-02-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0045_auto_20210221_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
        ),
    ]
