# Generated by Django 2.2 on 2021-02-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0046_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingmethod',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='international_cost',
        ),
    ]
