# Generated by Django 2.2 on 2021-02-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0047_auto_20210221_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
