# Generated by Django 2.2 on 2021-02-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0048_shippingmethod_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
