# Generated by Django 2.2 on 2021-02-21 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0050_carousel_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('subheader', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('number', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='carousel/')),
            ],
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='body',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='header',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='subheader',
        ),
        migrations.DeleteModel(
            name='CarouselImage',
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='carousel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop_app.Carousel'),
        ),
    ]
