# Generated by Django 2.2 on 2021-02-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0051_auto_20210221_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
