# Generated by Django 2.2 on 2021-02-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0052_carousel_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
